#ifndef CONSOLE_H_INCLUDED
#define CONSOLE_H_INCLUDED

#define CLEAR_CONSOLE()     system("cls")

#define COLOR(X)     system(X)

// 0.BACKGROUND_BLACK
#define BACKGROUND_BLACK_FONT_BLUE              "color 01"
#define BACKGROUND_BLACK_FONT_GREEN             "color 02"
#define BACKGROUND_BLACK_FONT_AQUA              "color 03"
#define BACKGROUND_BLACK_FONT_RED               "color 04"
#define BACKGROUND_BLACK_FONT_PURPLE            "color 05"
#define BACKGROUND_BLACK_FONT_YELLOW            "color 06"
#define BACKGROUND_BLACK_FONT_WHITE             "color 07"
#define BACKGROUND_BLACK_FONT_GRAY              "color 08"
#define BACKGROUND_BLACK_FONT_LIGHT_BLUE        "color 09"
#define BACKGROUND_BLACK_FONT_LIGHT_GREEN       "color 0A"
#define BACKGROUND_BLACK_FONT_LIGHT_AQUA        "color 0B"
#define BACKGROUND_BLACK_FONT_LIGHT_RED         "color 0C"
#define BACKGROUND_BLACK_FONT_LIGHT_PURPLE      "color 0D"
#define BACKGROUND_BLACK_FONT_LIGHT_YELLOW      "color 0E"
#define BACKGROUND_BLACK_FONT_LIGHT_WHITE       "color 0F"

// 1.BACKGROUND_BLUE
#define BACKGROUND_BLUE_FONT_BLACK             "color 10"
#define BACKGROUND_BLUE_FONT_GREEN             "color 12"
#define BACKGROUND_BLUE_FONT_AQUA              "color 13"
#define BACKGROUND_BLUE_FONT_RED               "color 14"
#define BACKGROUND_BLUE_FONT_PURPLE            "color 15"
#define BACKGROUND_BLUE_FONT_YELLOW            "color 16"
#define BACKGROUND_BLUE_FONT_WHITE             "color 17"
#define BACKGROUND_BLUE_FONT_GRAY              "color 18"
#define BACKGROUND_BLUE_FONT_LIGHT_BLUE        "color 19"
#define BACKGROUND_BLUE_FONT_LIGHT_GREEN       "color 1A"
#define BACKGROUND_BLUE_FONT_LIGHT_AQUA        "color 1B"
#define BACKGROUND_BLUE_FONT_LIGHT_RED         "color 1C"
#define BACKGROUND_BLUE_FONT_LIGHT_PURPLE      "color 1D"
#define BACKGROUND_BLUE_FONT_LIGHT_YELLOW      "color 1E"
#define BACKGROUND_BLUE_FONT_LIGHT_WHITE       "color 1F"

// 2.BACKGROUND_GREEN
#define BACKGROUND_GREEN_FONT_BLACK             "color 20"
#define BACKGROUND_GREEN_FONT_BLUE              "color 21"
#define BACKGROUND_GREEN_FONT_AQUA              "color 23"
#define BACKGROUND_GREEN_FONT_RED               "color 24"
#define BACKGROUND_GREEN_FONT_PURPLE            "color 25"
#define BACKGROUND_GREEN_FONT_YELLOW            "color 26"
#define BACKGROUND_GREEN_FONT_WHITE             "color 27"
#define BACKGROUND_GREEN_FONT_GRAY              "color 28"
#define BACKGROUND_GREEN_FONT_LIGHT_BLUE        "color 29"
#define BACKGROUND_GREEN_FONT_LIGHT_GREEN       "color 2A"
#define BACKGROUND_GREEN_FONT_LIGHT_AQUA        "color 2B"
#define BACKGROUND_GREEN_FONT_LIGHT_RED         "color 2C"
#define BACKGROUND_GREEN_FONT_LIGHT_PURPLE      "color 2D"
#define BACKGROUND_GREEN_FONT_LIGHT_YELLOW      "color 2E"
#define BACKGROUND_GREEN_FONT_LIGHT_WHITE       "color 2F"

// 3.BACKGROUND_AQUA
#define BACKGROUND_AQUA_FONT_BLACK             "color 30"
#define BACKGROUND_AQUA_FONT_BLUE              "color 31"
#define BACKGROUND_AQUA_FONT_GREEN             "color 32"
#define BACKGROUND_AQUA_FONT_RED               "color 34"
#define BACKGROUND_AQUA_FONT_PURPLE            "color 35"
#define BACKGROUND_AQUA_FONT_YELLOW            "color 36"
#define BACKGROUND_AQUA_FONT_WHITE             "color 37"
#define BACKGROUND_AQUA_FONT_GRAY              "color 38"
#define BACKGROUND_AQUA_FONT_LIGHT_BLUE        "color 39"
#define BACKGROUND_AQUA_FONT_LIGHT_GREEN       "color 3A"
#define BACKGROUND_AQUA_FONT_LIGHT_AQUA        "color 3B"
#define BACKGROUND_AQUA_FONT_LIGHT_RED         "color 3C"
#define BACKGROUND_AQUA_FONT_LIGHT_PURPLE      "color 3D"
#define BACKGROUND_AQUA_FONT_LIGHT_YELLOW      "color 3E"
#define BACKGROUND_AQUA_FONT_LIGHT_WHITE       "color 3F"

// 4.BACKGROUND_RED
#define BACKGROUND_RED_FONT_BLACK             "color 40"
#define BACKGROUND_RED_FONT_BLUE              "color 41"
#define BACKGROUND_RED_FONT_GREEN             "color 42"
#define BACKGROUND_RED_FONT_AQUA              "color 43"
#define BACKGROUND_RED_FONT_PURPLE            "color 45"
#define BACKGROUND_RED_FONT_YELLOW            "color 46"
#define BACKGROUND_RED_FONT_WHITE             "color 47"
#define BACKGROUND_RED_FONT_GRAY              "color 48"
#define BACKGROUND_RED_FONT_LIGHT_BLUE        "color 49"
#define BACKGROUND_RED_FONT_LIGHT_GREEN       "color 4A"
#define BACKGROUND_RED_FONT_LIGHT_AQUA        "color 4B"
#define BACKGROUND_RED_FONT_LIGHT_RED         "color 4C"
#define BACKGROUND_RED_FONT_LIGHT_PURPLE      "color 4D"
#define BACKGROUND_RED_FONT_LIGHT_YELLOW      "color 4E"
#define BACKGROUND_RED_FONT_LIGHT_WHITE       "color 4F"

// 5.BACKGROUND_PURPLE
#define BACKGROUND_PURPLE_FONT_BLACK             "color 50"
#define BACKGROUND_PURPLE_FONT_BLUE              "color 51"
#define BACKGROUND_PURPLE_FONT_GREEN             "color 52"
#define BACKGROUND_PURPLE_FONT_AQUA              "color 53"
#define BACKGROUND_PURPLE_FONT_RED               "color 54"
#define BACKGROUND_PURPLE_FONT_YELLOW            "color 56"
#define BACKGROUND_PURPLE_FONT_WHITE             "color 57"
#define BACKGROUND_PURPLE_FONT_GRAY              "color 58"
#define BACKGROUND_PURPLE_FONT_LIGHT_BLUE        "color 59"
#define BACKGROUND_PURPLE_FONT_LIGHT_GREEN       "color 5A"
#define BACKGROUND_PURPLE_FONT_LIGHT_AQUA        "color 5B"
#define BACKGROUND_PURPLE_FONT_LIGHT_RED         "color 5C"
#define BACKGROUND_PURPLE_FONT_LIGHT_PURPLE      "color 5D"
#define BACKGROUND_PURPLE_FONT_LIGHT_YELLOW      "color 5E"
#define BACKGROUND_PURPLE_FONT_LIGHT_WHITE       "color 5F"

// 6.BACKGROUND_YELLOW
#define BACKGROUND_YELLOW_FONT_BLACK             "color 60"
#define BACKGROUND_YELLOW_FONT_BLUE              "color 61"
#define BACKGROUND_YELLOW_FONT_GREEN             "color 62"
#define BACKGROUND_YELLOW_FONT_AQUA              "color 63"
#define BACKGROUND_YELLOW_FONT_RED               "color 64"
#define BACKGROUND_YELLOW_FONT_PURPLE            "color 65"
#define BACKGROUND_YELLOW_FONT_WHITE             "color 67"
#define BACKGROUND_YELLOW_FONT_GRAY              "color 68"
#define BACKGROUND_YELLOW_FONT_LIGHT_BLUE        "color 69"
#define BACKGROUND_YELLOW_FONT_LIGHT_GREEN       "color 6A"
#define BACKGROUND_YELLOW_FONT_LIGHT_AQUA        "color 6B"
#define BACKGROUND_YELLOW_FONT_LIGHT_RED         "color 6C"
#define BACKGROUND_YELLOW_FONT_LIGHT_PURPLE      "color 6D"
#define BACKGROUND_YELLOW_FONT_LIGHT_YELLOW      "color 6E"
#define BACKGROUND_YELLOW_FONT_LIGHT_WHITE       "color 6F"

// 7.BACKGROUND_WHITE
#define BACKGROUND_WHITE_FONT_BLACK             "color 70"
#define BACKGROUND_WHITE_FONT_BLUE              "color 71"
#define BACKGROUND_WHITE_FONT_GREEN             "color 72"
#define BACKGROUND_WHITE_FONT_AQUA              "color 73"
#define BACKGROUND_WHITE_FONT_RED               "color 74"
#define BACKGROUND_WHITE_FONT_PURPLE            "color 75"
#define BACKGROUND_WHITE_FONT_YELLOW            "color 76"
#define BACKGROUND_WHITE_FONT_GRAY              "color 78"
#define BACKGROUND_WHITE_FONT_LIGHT_BLUE        "color 79"
#define BACKGROUND_WHITE_FONT_LIGHT_GREEN       "color 7A"
#define BACKGROUND_WHITE_FONT_LIGHT_AQUA        "color 7B"
#define BACKGROUND_WHITE_FONT_LIGHT_RED         "color 7C"
#define BACKGROUND_WHITE_FONT_LIGHT_PURPLE      "color 7D"
#define BACKGROUND_WHITE_FONT_LIGHT_YELLOW      "color 7E"
#define BACKGROUND_WHITE_FONT_LIGHT_WHITE       "color 7F"

// 8.BACKGROUND_GRAY
#define BACKGROUND_GRAY_FONT_BLACK             "color 80"
#define BACKGROUND_GRAY_FONT_BLUE              "color 81"
#define BACKGROUND_GRAY_FONT_GREEN             "color 82"
#define BACKGROUND_GRAY_FONT_AQUA              "color 83"
#define BACKGROUND_GRAY_FONT_RED               "color 84"
#define BACKGROUND_GRAY_FONT_PURPLE            "color 85"
#define BACKGROUND_GRAY_FONT_YELLOW            "color 86"
#define BACKGROUND_GRAY_FONT_WHITE             "color 87"
#define BACKGROUND_GRAY_FONT_LIGHT_BLUE        "color 89"
#define BACKGROUND_GRAY_FONT_LIGHT_GREEN       "color 8A"
#define BACKGROUND_GRAY_FONT_LIGHT_AQUA        "color 8B"
#define BACKGROUND_GRAY_FONT_LIGHT_RED         "color 8C"
#define BACKGROUND_GRAY_FONT_LIGHT_PURPLE      "color 8D"
#define BACKGROUND_GRAY_FONT_LIGHT_YELLOW      "color 8E"
#define BACKGROUND_GRAY_FONT_LIGHT_WHITE       "color 8F"

// 9.BACKGROUND_LIGHT_BLUE
#define BACKGROUND_LIGHT_BLUE_FONT_BLACK             "color 90"
#define BACKGROUND_LIGHT_BLUE_FONT_BLUE              "color 91"
#define BACKGROUND_LIGHT_BLUE_FONT_GREEN             "color 92"
#define BACKGROUND_LIGHT_BLUE_FONT_AQUA              "color 93"
#define BACKGROUND_LIGHT_BLUE_FONT_RED               "color 94"
#define BACKGROUND_LIGHT_BLUE_FONT_PURPLE            "color 95"
#define BACKGROUND_LIGHT_BLUE_FONT_YELLOW            "color 96"
#define BACKGROUND_LIGHT_BLUE_FONT_WHITE             "color 97"
#define BACKGROUND_LIGHT_BLUE_FONT_GRAY              "color 98"
#define BACKGROUND_LIGHT_BLUE_FONT_LIGHT_GREEN       "color 9A"
#define BACKGROUND_LIGHT_BLUE_FONT_LIGHT_AQUA        "color 9B"
#define BACKGROUND_LIGHT_BLUE_FONT_LIGHT_RED         "color 9C"
#define BACKGROUND_LIGHT_BLUE_FONT_LIGHT_PURPLE      "color 9D"
#define BACKGROUND_LIGHT_BLUE_FONT_LIGHT_YELLOW      "color 9E"
#define BACKGROUND_LIGHT_BLUE_FONT_LIGHT_WHITE       "color 9F"

// A.BACKGROUND_LIGHT_GREEN
#define BACKGROUND_LIGHT_GREEN_FONT_BLACK             "color A0"
#define BACKGROUND_LIGHT_GREEN_FONT_BLUE              "color A1"
#define BACKGROUND_LIGHT_GREEN_FONT_GREEN             "color A2"
#define BACKGROUND_LIGHT_GREEN_FONT_AQUA              "color A3"
#define BACKGROUND_LIGHT_GREEN_FONT_RED               "color A4"
#define BACKGROUND_LIGHT_GREEN_FONT_PURPLE            "color A5"
#define BACKGROUND_LIGHT_GREEN_FONT_YELLOW            "color A6"
#define BACKGROUND_LIGHT_GREEN_FONT_WHITE             "color A7"
#define BACKGROUND_LIGHT_GREEN_FONT_GRAY              "color A8"
#define BACKGROUND_LIGHT_GREEN_FONT_LIGHT_BLUE        "color A9"
#define BACKGROUND_LIGHT_GREEN_FONT_LIGHT_AQUA        "color AB"
#define BACKGROUND_LIGHT_GREEN_FONT_LIGHT_RED         "color AC"
#define BACKGROUND_LIGHT_GREEN_FONT_LIGHT_PURPLE      "color AD"
#define BACKGROUND_LIGHT_GREEN_FONT_LIGHT_YELLOW      "color AE"
#define BACKGROUND_LIGHT_GREEN_FONT_LIGHT_WHITE       "color AF"

// B.BACKGROUND_LIGHT_AQUA
#define BACKGROUND_LIGHT_AQUA_FONT_BLACK             "color B0"
#define BACKGROUND_LIGHT_AQUA_FONT_BLUE              "color B1"
#define BACKGROUND_LIGHT_AQUA_FONT_GREEN             "color B2"
#define BACKGROUND_LIGHT_AQUA_FONT_AQUA              "color B3"
#define BACKGROUND_LIGHT_AQUA_FONT_RED               "color B4"
#define BACKGROUND_LIGHT_AQUA_FONT_PURPLE            "color B5"
#define BACKGROUND_LIGHT_AQUA_FONT_YELLOW            "color B6"
#define BACKGROUND_LIGHT_AQUA_FONT_WHITE             "color B7"
#define BACKGROUND_LIGHT_AQUA_FONT_GRAY              "color B8"
#define BACKGROUND_LIGHT_AQUA_FONT_LIGHT_BLUE        "color B9"
#define BACKGROUND_LIGHT_AQUA_FONT_LIGHT_GREEN       "color BA"
#define BACKGROUND_LIGHT_AQUA_FONT_LIGHT_RED         "color BC"
#define BACKGROUND_LIGHT_AQUA_FONT_LIGHT_PURPLE      "color BD"
#define BACKGROUND_LIGHT_AQUA_FONT_LIGHT_YELLOW      "color BE"
#define BACKGROUND_LIGHT_AQUA_FONT_LIGHT_WHITE       "color BF"

// C.BACKGROUND_LIGHT_RED
#define BACKGROUND_LIGHT_RED_FONT_BLACK             "color C0"
#define BACKGROUND_LIGHT_RED_FONT_BLUE              "color C1"
#define BACKGROUND_LIGHT_RED_FONT_GREEN             "color C2"
#define BACKGROUND_LIGHT_RED_FONT_AQUA              "color C3"
#define BACKGROUND_LIGHT_RED_FONT_RED               "color C4"
#define BACKGROUND_LIGHT_RED_FONT_PURPLE            "color C5"
#define BACKGROUND_LIGHT_RED_FONT_YELLOW            "color C6"
#define BACKGROUND_LIGHT_RED_FONT_WHITE             "color C7"
#define BACKGROUND_LIGHT_RED_FONT_GRAY              "color C8"
#define BACKGROUND_LIGHT_RED_FONT_LIGHT_BLUE        "color C9"
#define BACKGROUND_LIGHT_RED_FONT_LIGHT_GREEN       "color CA"
#define BACKGROUND_LIGHT_RED_FONT_LIGHT_AQUA        "color CB"
#define BACKGROUND_LIGHT_RED_FONT_LIGHT_PURPLE      "color CD"
#define BACKGROUND_LIGHT_RED_FONT_LIGHT_YELLOW      "color CE"
#define BACKGROUND_LIGHT_RED_FONT_LIGHT_WHITE       "color CF"

// D.BACKGROUND_LIGHT_PURPLE
#define BACKGROUND_LIGHT_PURPLE_FONT_BLACK             "color D0"
#define BACKGROUND_LIGHT_PURPLE_FONT_BLUE              "color D1"
#define BACKGROUND_LIGHT_PURPLE_FONT_GREEN             "color D2"
#define BACKGROUND_LIGHT_PURPLE_FONT_AQUA              "color D3"
#define BACKGROUND_LIGHT_PURPLE_FONT_RED               "color D4"
#define BACKGROUND_LIGHT_PURPLE_FONT_PURPLE            "color D5"
#define BACKGROUND_LIGHT_PURPLE_FONT_YELLOW            "color D6"
#define BACKGROUND_LIGHT_PURPLE_FONT_WHITE             "color D7"
#define BACKGROUND_LIGHT_PURPLE_FONT_GRAY              "color D8"
#define BACKGROUND_LIGHT_PURPLE_FONT_LIGHT_BLUE        "color D9"
#define BACKGROUND_LIGHT_PURPLE_FONT_LIGHT_GREEN       "color DA"
#define BACKGROUND_LIGHT_PURPLE_FONT_LIGHT_AQUA        "color DB"
#define BACKGROUND_LIGHT_PURPLE_FONT_LIGHT_RED         "color DC"
#define BACKGROUND_LIGHT_PURPLE_FONT_LIGHT_YELLOW      "color DE"
#define BACKGROUND_LIGHT_PURPLE_FONT_LIGHT_WHITE       "color DF"

// E.BACKGROUND_LIGHT_YELLOW
#define BACKGROUND_LIGHT_YELLOW_FONT_BLACK             "color E0"
#define BACKGROUND_LIGHT_YELLOW_FONT_BLUE              "color E1"
#define BACKGROUND_LIGHT_YELLOW_FONT_GREEN             "color E2"
#define BACKGROUND_LIGHT_YELLOW_FONT_AQUA              "color E3"
#define BACKGROUND_LIGHT_YELLOW_FONT_RED               "color E4"
#define BACKGROUND_LIGHT_YELLOW_FONT_PURPLE            "color E5"
#define BACKGROUND_LIGHT_YELLOW_FONT_YELLOW            "color E6"
#define BACKGROUND_LIGHT_YELLOW_FONT_WHITE             "color E7"
#define BACKGROUND_LIGHT_YELLOW_FONT_GRAY              "color E8"
#define BACKGROUND_LIGHT_YELLOW_FONT_LIGHT_BLUE        "color E9"
#define BACKGROUND_LIGHT_YELLOW_FONT_LIGHT_GREEN       "color EA"
#define BACKGROUND_LIGHT_YELLOW_FONT_LIGHT_AQUA        "color EB"
#define BACKGROUND_LIGHT_YELLOW_FONT_LIGHT_RED         "color EC"
#define BACKGROUND_LIGHT_YELLOW_FONT_LIGHT_PURPLE      "color ED"
#define BACKGROUND_LIGHT_YELLOW_FONT_LIGHT_WHITE       "color EF"

// F.BACKGROUND_LIGHT_WHITE
#define BACKGROUND_LIGHT_WHITE_FONT_BLACK             "color F0"
#define BACKGROUND_LIGHT_WHITE_FONT_BLUE              "color F1"
#define BACKGROUND_LIGHT_WHITE_FONT_GREEN             "color F2"
#define BACKGROUND_LIGHT_WHITE_FONT_AQUA              "color F3"
#define BACKGROUND_LIGHT_WHITE_FONT_RED               "color F4"
#define BACKGROUND_LIGHT_WHITE_FONT_PURPLE            "color F5"
#define BACKGROUND_LIGHT_WHITE_FONT_YELLOW            "color F6"
#define BACKGROUND_LIGHT_WHITE_FONT_WHITE             "color F7"
#define BACKGROUND_LIGHT_WHITE_FONT_GRAY              "color F8"
#define BACKGROUND_LIGHT_WHITE_FONT_LIGHT_BLUE        "color F9"
#define BACKGROUND_LIGHT_WHITE_FONT_LIGHT_GREEN       "color FA"
#define BACKGROUND_LIGHT_WHITE_FONT_LIGHT_AQUA        "color FB"
#define BACKGROUND_LIGHT_WHITE_FONT_LIGHT_RED         "color FC"
#define BACKGROUND_LIGHT_WHITE_FONT_LIGHT_PURPLE      "color FD"
#define BACKGROUND_LIGHT_WHITE_FONT_LIGHT_YELLOW      "color FE"

#endif // CONSOLE_H_INCLUDED
